=== petyakazakova/XML_schema/my-schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- namespace -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">

<xs:element name="employees">
	<xs:complexType>
		<!-- define that employees info should always come in sequence --> 
		<xs:sequence>
			<xs:element name="employee" minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>	
</xs:element>

<xs:element>
	<xs:complexType>
		<xs:all>
			<xs:element name="firstname" type="xs:string"></xs:element>
			<xs:element name="lastname" type="xs:string"></xs:element>
			<xs:element name="email" type="xs:string"></xs:element>
		</xs:all>
	</xs:complexType>
</xs:element>

<xs:element name="phone" > 
	<xs:complexType>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string"> <!-- restriction: string should be equal to either work or mobile -->
					<xs:enumeration value="work"></xs:enumeration>
					<xs:enumeration value="mobile"></xs:enumeration>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:element>

</xs:schema>

=== petyakazakova/XML_schema/xmlFile.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/css" href="stylesheet.css" ?>

<employees xmlns:xs="https://www.w3.org/2001/XML-Schema-instance" xs:noNamespaceSchemaLocation="./my-schema.xsd">
  <employee>
    <firstname>Petya</firstname>
    <lastname>Kazakova</lastname>
    <phone type="work">45607412</phone>
    <phone type="mobile">34582017</phone>
    <email>pkazakova@gmail.com</email>
  </employee>

  <employee>
    <firstname>Svilena</firstname>
    <lastname>Koleva</lastname>
    <phone type="work">45607412</phone>
    <phone type="mobile">34582017</phone>
    <email>skoleva@gmail.com</email>
  </employee> 
  
  <employee>
    <firstname>Andreas</firstname>
    <lastname>Brolund</lastname>
    <phone type="work">45607412</phone>
    <phone type="mobile">34582017</phone>
    <email>abrolund@gmail.com</email>
  </employee> 

</employees>
